### PR TITLE
fixed a bug

### PR DESCRIPTION
**Pull request by Abemelekermi**
There was a bug where if the error appears on the screen you can't type anything you have to manually clear so now if error happens and when you click any digit the error message gets removed

### CODE REVIEW

**Comment by Abemelekermi** [comment]
merge it yeftne

**Review by kerodkibatu — CHANGES_REQUESTED** [review]
There are unnecessary console.writelines fix those and you're ready to go. 

PS. Congrats on contributing to your first .NET repo!

**Comment by Abemelekermi** [comment]
I have removed unnecessary console.writelines

**Review by kerodkibatu — APPROVED** [review]
Great Job! Merged👍

**Pull request merged**
